"""
fetchers/tavily_fetcher.py — Tavily Web Search Fetcher (fallback)

Generic web search fallback that works for ANY topic. Runs up to 3
search query variants (generated by IntentExtractor) in sequence and
deduplicates results by URL.
"""

from typing import List, Dict, Any
from tavily import TavilyClient
from .base import logger, normalize_item


def fetch_tavily(state, config) -> List[Dict[str, Any]]:
    """
    Searches Tavily using all available query variants from state.search_queries.
    Falls back to core_topic alone if no query variants were generated.
    """
    search_queries = getattr(state, "search_queries", None) or [getattr(state, "core_topic", "")]
    search_queries = [q for q in search_queries if q]   # drop any empty entries

    items: List[Dict[str, Any]] = []

    if not config.TAVILY_API_KEY:
        logger.error("Tavily API key missing; skipping Tavily.")
        return items

    if not search_queries:
        logger.info("No search queries available for Tavily; skipping.")
        return items

    client = TavilyClient(api_key=config.TAVILY_API_KEY)
    all_results = []
    content_intent = getattr(state, "content_intent", "") or ""
    is_news = content_intent == "news" or any(w in getattr(state, "core_topic", "").lower() for w in ["news", "latest", "update", "release", "announced", "today"])

    for query in search_queries[:3]:
        try:
            search_kwargs: Dict[str, Any] = {
                "query": query,
                "search_depth": "advanced",
                "max_results": 10,
                "include_answer": True,
            }
            if is_news:
                search_kwargs["topic"] = "news"
                search_kwargs["days"] = 7

            response = client.search(**search_kwargs)
            results = response.get("results", [])
            # If an overall direct synthesized answer is provided, inject it as top knowledge snippet
            if response.get("answer") and not any(r.get("url") == "tavily:synthesized_answer" for r in all_results):
                all_results.append({
                    "title": f"Tavily Deep Synthesis: {query}",
                    "url": f"https://tavily.com/search?q={query}",
                    "content": response.get("answer"),
                    "score": 1.0,
                })
            all_results.extend(results)
        except Exception as e:
            logger.error(f"Tavily advanced search query '{query}' failed: {e}")

    # Deduplicate by URL — different query variants often surface the same page
    seen_urls = set()
    for res in all_results:
        url = res.get("url", "")
        if url and url not in seen_urls:
            seen_urls.add(url)
            items.append(normalize_item(
                title=res.get("title", ""),
                link=url,
                summary=res.get("content", "")[:300],
                source="tavily",
                score=res.get("score", 0),
            ))

    logger.info(f"Tavily returned {len(items)} unique items from {len(search_queries)} queries.")
    return items