"""
core/state.py — TrendForge Shared Pipeline State

Single TypedDict that flows through every layer of the pipeline.
Every component reads from and writes to this same state — this file
is the single source of truth for what fields exist and what they mean.
"""

from typing import TypedDict, List, Dict


class TrendForgeState(TypedDict):

    # ── RAW INPUT ─────────────────────────────────────────────
    raw_prompt: str                     # Exactly what the user typed, any length
    session_id: str                     # Unique ID for this run

    # ── PARSED INTENT (set by understanding/prompt_parser.py) ─
    core_topic: str                     # Clean extracted topic, e.g. "machine learning projects"
    platform: str                       # instagram | youtube | linkedin | tiktok
    post_count: int                     # How many posts to generate (default 5)
    content_type: str                   # posts | script | thread | carousel
    special_requests: List[str]         # e.g. ["github_links", "bullet_points"]
    detected_category: str              # tech | business | lifestyle | entertainment | education | news | unknown
    content_intent: str                 # showcase | educate | news | inspire | review
    is_long_prompt: bool                # True if raw_prompt exceeds ~120 chars

    # ── SOURCE ROUTING (set by routing/router_orchestrator.py) ─
    selected_sources: List[str]         # e.g. ["github", "tavily"]
    routing_method: str                 # "rules" | "llm" | "fallback_general"

    # ── FETCHED DATA (set by fetchers/fetcher_orchestrator.py) ─
    fetched_data: Dict[str, List[Dict]] # source_name -> list of normalized items
    fetch_summary: str                  # primary search query used
    search_queries: List[str]           # all search query variants generated by intent extractor
    total_items_fetched: int            # total raw items across all sources
    trend_insight: str                  # 2-3 sentence "why this is trending" blurb from the model's
                                         # JSON response. Distinct from fetch_summary on purpose — these
                                         # were previously colliding, so a missing trend_insight in a
                                         # malformed LLM response silently displayed the search query
                                         # instead. Defaults to "" (formatter should just omit the
                                         # section when empty, not show a fallback value).
    already_covered: List[Dict]         # previously-generated {title, link} pairs for this topic
                                         # + platform, pulled from session_store.get_already_covered()
                                         # in main.py before generation. Empty list if none found or
                                         # lookup failed — generation should treat empty the same as
                                         # "no history available", never as an error.

    # ── GENERATED CONTENT (set by generation/content_generator.py) ─
    generated_posts: List[Dict]         # list of post dicts: hook, summary, link, caption, hashtags
    final_output: str                   # complete formatted string, ready to print/save
    content_generation_engine: str      # "Gemini" | "Groq-LLaMA3" | "None" — which engine actually
                                         # served the content_generation tokens this run. Set once,
                                         # in content_generator.py, right after the engine is decided.
                                         # Downstream reporting (token_tracker.py, formatter.py) reads
                                         # this instead of assuming Gemini always ran.

    # ── TOKEN TRACKING ────────────────────────────────────────
    # Keys: "prompt_parsing", "source_routing", "data_fetching", "content_generation"
    tokens: Dict[str, int]

    # ── SYSTEM / DIAGNOSTICS ──────────────────────────────────
    errors: List[str]                   # non-fatal errors — pipeline continues despite these
    warnings: List[str]                 # non-fatal warnings
    logs: List[str]                     # execution trace — used for debugging, keep populated
    sources_used: List[str]             # which sources actually returned data (subset of selected_sources)

    # ── PHASE 1: GATE STATE (workflow/gates.py) ───────────────
    data_starved: bool                       # True if fetch retries exhausted with insufficient data.
                                              # When True, link fields are optional regardless of
                                              # content_intent (overrides the normal per-intent rule).
    fetch_retry_count: int                   # current fetch-quality retry attempt, capped at 2
    generation_retry_count: int              # current post-validation retry attempt, capped at 2
    generation_validation_errors: List[str]  # Tier 1 validation failure reasons from the last check

    # ── PHASE 1 INTEGRATION: explicit gate decisions ──────────
    # Set exactly once by node_evaluate_fetch/node_evaluate_generation
    # (workflow/nodes.py), using the correct pre-increment retry count.
    # The routing functions in workflow/graph.py read these directly and
    # NEVER recompute the decision — recomputing after the node's own
    # increment produced an off-by-one bug (verified via simulation:
    # cut the retry loop short by one attempt) and, in the alternate fix
    # attempted, an infinite loop in the "still invalid on the final
    # allowed attempt" case. A frozen retry-count integer alone can't
    # distinguish "just approved this retry" from "already gave up" once
    # it stops changing — these booleans remove that ambiguity entirely.
    fetch_should_retry: bool
    generation_should_retry: bool


def create_initial_state(raw_prompt: str, session_id: str) -> TrendForgeState:
    """
    Factory — the ONLY place a fresh state should be created.
    Every field gets an explicit default here so no field is ever
    silently missing later in the pipeline.
    """
    return TrendForgeState(
        raw_prompt=raw_prompt,
        session_id=session_id,

        core_topic="",
        platform="instagram",
        post_count=5,
        content_type="posts",
        special_requests=[],
        detected_category="unknown",
        content_intent="",
        is_long_prompt=len(raw_prompt) > 120,

        selected_sources=[],
        routing_method="",

        fetched_data={},
        fetch_summary="",
        search_queries=[],
        total_items_fetched=0,
        trend_insight="",
        already_covered=[],

        generated_posts=[],
        final_output="",
        content_generation_engine="",

        tokens={
            "prompt_parsing": 0,
            "source_routing": 0,
            "data_fetching": 0,
            "content_generation": 0,
        },

        errors=[],
        warnings=[],
        logs=[],
        sources_used=[],

        data_starved=False,
        fetch_retry_count=0,
        generation_retry_count=0,
        generation_validation_errors=[],
        fetch_should_retry=False,
        generation_should_retry=False,
    )


def add_log(state: TrendForgeState, message: str) -> None:
    """Appends to logs in place. Use liberally — logs are the primary debugging tool."""
    state["logs"].append(message)


def add_error(state: TrendForgeState, message: str) -> None:
    """Appends to errors in place. Non-fatal — pipeline should continue after this."""
    state["errors"].append(message)


def add_tokens(state: TrendForgeState, layer: str, count: int) -> None:
    """
    The ONLY function that should ever update state['tokens'].
    Do not mutate state['tokens'] directly anywhere else in the codebase —
    that would create a second source of truth for token counts.
    """
    if layer in state["tokens"]:
        state["tokens"][layer] += count
    else:
        state["tokens"][layer] = count


def get_total_tokens(state: TrendForgeState) -> int:
    """Returns total tokens used across all layers."""
    return sum(state["tokens"].values())