"""
fetchers/tavily_fetcher.py — Tavily Web Search Fetcher (fallback)

Generic web search fallback that works for ANY topic. Runs up to 3
search query variants (generated by IntentExtractor) in sequence and
deduplicates results by URL.
"""

from typing import List, Dict, Any
from tavily import TavilyClient
from .base import logger, normalize_item


def fetch_tavily(state, config) -> List[Dict[str, Any]]:
    """
    Searches Tavily using all available query variants from state.search_queries.
    Falls back to core_topic alone if no query variants were generated.
    """
    search_queries = getattr(state, "search_queries", None) or [getattr(state, "core_topic", "")]
    search_queries = [q for q in search_queries if q]   # drop any empty entries

    items: List[Dict[str, Any]] = []

    if not config.TAVILY_API_KEY:
        logger.error("Tavily API key missing; skipping Tavily.")
        return items

    if not search_queries:
        logger.info("No search queries available for Tavily; skipping.")
        return items

    client = TavilyClient(api_key=config.TAVILY_API_KEY)
    all_results = []

    for query in search_queries[:3]:
        try:
            response = client.search(
                query=query,
                search_depth="advanced",
                max_results=10,
            )
            all_results.extend(response.get("results", []))
        except Exception as e:
            logger.error(f"Tavily query '{query}' failed: {e}")

    # Deduplicate by URL — different query variants often surface the same page
    seen_urls = set()
    for res in all_results:
        url = res.get("url", "")
        if url and url not in seen_urls:
            seen_urls.add(url)
            items.append(normalize_item(
                title=res.get("title", ""),
                link=url,
                summary=res.get("content", "")[:300],
                source="tavily",
                score=res.get("score", 0),
            ))

    logger.info(f"Tavily returned {len(items)} unique items from {len(search_queries)} queries.")
    return items